# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='first_priority',
            field=models.CharField(blank=True, choices=[('fitness', 'fitness'), ('nutrition', 'nutrition'), ('mindset', 'mindset')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_time_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='second_priority',
            field=models.CharField(blank=True, choices=[('fitness', 'fitness'), ('nutrition', 'nutrition'), ('mindset', 'mindset')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='third_priority',
            field=models.CharField(blank=True, choices=[('fitness', 'fitness'), ('nutrition', 'nutrition'), ('mindset', 'mindset')], max_length=100, null=True),
        ),
    ]
