# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-15 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191115_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_time_user',
        ),
    ]
